/*
 * csi_presence.h - on-device presence classifier fed by raw CSI records.
 *
 * Requires (generated by csi_train_export.py, copy into source/):
 *     csi_model.h, csi_model_config.h   (and csi_selftest.h if SELFTEST is 1)
 */
#ifndef CSI_PRESENCE_H_
#define CSI_PRESENCE_H_

#include <stddef.h>
#include <stdint.h>

/* Majority vote over the last N classifications, to stop the output flickering. */
#ifndef CSI_VOTE_N
#define CSI_VOTE_N 3U
#endif

/* 1 = at boot, run the embedded test windows through featurize + model. */
#ifndef CSI_PRESENCE_SELFTEST
#define CSI_PRESENCE_SELFTEST 0
#endif

/* Second output on a UART pin: define these in the project's preprocessor
 * settings (or here) to enable it. Leave CSI_PRES_UART_BASE undefined for
 * console-only output.
 *   CSI_PRES_UART_BASE    USART instance, e.g. USART0
 *   CSI_PRES_UART_CLK_HZ  clock of that FLEXCOMM, e.g. CLOCK_GetFlexCommClkFreq(0U)
 */
#ifndef CSI_PRES_UART_BAUD
#define CSI_PRES_UART_BAUD 115200U
#endif

/* Optional: define CSI_PRES_OUT_HOOK(cls) to drive a GPIO/LED from the class. */

/* Starts the NDJSON output task (csi_uart_out.c) and optionally runs the self-test. */
int csi_presence_init(void);

/* Milliseconds since the last valid record from the AP was accepted. */
uint32_t csi_presence_ms_since_feed(void);

/* Records rejected by validation (bad header, or a different data size than trained). */
uint32_t csi_presence_rejected(void);

/* Feed ONE complete raw CSI record (48-byte header | CSI data | 4-byte tail).
 * Call from a task, never from the Wi-Fi driver callback. */
void csi_presence_feed(const uint8_t *rec, size_t len);

#endif /* CSI_PRESENCE_H_ */
